docentes = [
  "MARIA BERNARDA SALAZAR SANCHEZ",
  "DIEGO JOSE LUIS BOTIA VALDERRAMA",
  "JOHN FREDDY DUITAMA MUÑOZ",
  "FREDY ALEXANDER RIVERA VELEZ",
  "LUZ VIVIANA COBALEDA ESTEPA",
  "CARLOS MARIO SIERRA DUQUE",
  "JULIAN DAVID ARIAS LONDOÑO",
  
]